[package]
name = "zero2prod"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.1"
axum-test = "17.2.0"
reqwest = "0.12.14"
serde_json = "1.0.140"
tokio = { version = "1.44.0", features = ["macros", "rt-multi-thread"] }
tower-http = "0.6.2"
