# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: '2.1'
orbs:
  coveralls: coveralls/coveralls@2.2.5
  codecov: codecov/codecov@5

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
jobs:
  coverage:
    docker:
      - image: xd009642/tarpaulin
    steps:
      - checkout
      - run:
          name: Coverage with docker
          command: cargo tarpaulin --ignore-tests --out xml
      - run:
          name: Generate code coverage
          command: cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info
      - run:
          name: Generate report
          command: cargo llvm-cov report --html --output-dir coverage
      - store_artifacts:
          path: coverage/
      - codecov/upload
      - coveralls/upload
workflows:
  test_then_upload:
    jobs:
      - coverage
