# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: '2.1'
orbs:
  coveralls: coveralls/coveralls@2.2.5
  codecov: codecov/codecov@5

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
jobs:
  coverage:
    steps:
      - checkout
      - run:
          name: Coverage with docker
          command: cargo tarpaulin --verbose --all-features --workspace --timeout 120 --out xml
      - codecov/upload
      - coveralls/upload
workflows:
  test_then_upload:
    jobs:
      - coverage
